### ISSUE TITLE
Args out of range #<killed buffer>, 0, 0

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [benma/visual-regexp-steroids.el#13]
Original post in StackExchange [here](http://emacs.stackexchange.com/questions/16462/multiple-cursors-with-regexps).

-----
I have been trying to use [`visual-regexp-steroids`](https://github.com/benma/visual-regexp-steroids.el/) without luck (a thread on this package can be found [here](http://emacs.stackexchange.com/questions/69/how-can-i-test-and-use-a-perl-regular-expression-interactively))

When I do `vr/replace (C-c p)`, I get a prompt in the minibuffer. I can enter regexps and Emacs shows interactively every match in the buffer. So far so good. 

The problem comes when I click `RET` and then enter another string (the one I want to replace my matches with). If I now do `RET` (to do the actual replacements), I get the following message in the mini-buffer:

    Args out of range #<killed buffer>, 0, 0

Why? How can I debug the problem and get it to work?

**Comment by benma** [comment]
Sorry for taking so long to respond, I have been away on travels.

Since I am not experiencing this problem, it would be helpful if you could provide a setup in which I can reproduce this (minimal init.el, emacs version, etc. to reproduce).

To zero in on the problem:
- Does [visual-regexp](https://github.com/benma/visual-regexp.el/) (without the steroids add-on) work for you?
- Does it work if you use the emacs engine? Use `vr/select-replace`, choose the emacs engine.

**Comment by amelio-vazquez-reina** [comment]
Thanks @benma for looking into it. I will definitely try those suggestions this afternoon and post what I get.

**Comment by amelio-vazquez-reina** [comment]
Hi @benma 

* `vr/select-replace` works perfectly well with the `emacs` engine, but it fails with `Args out of range: #<killed buffer>, 0, 0` with the `python` engine.  What Python version am I supposed to use with it? I think I am using `Python 3.4.3` under the hood.

**Comment by amelio-vazquez-reina** [comment]
Also, `vr/mc-mark` works without problem, but `vr/replace` doesn't.

**Comment by amelio-vazquez-reina** [comment]
In case it helps, I am using:

`GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F27))`

**Comment by benma** [comment]
This emacs and Python version should both work. Since you are seeing the matches when entering the search string, Emacs and Python are able to talk.

Please set `debug-on-error` to `t` (`M-x toggle-debug-on-error`) and paste the stack trace. 
Do this while running emacs with `emacs -q` (which loads Emacs without any customizations), and try it in the default scratch buffer. You can use `M-x load-library` to load visual-regexp-steroids.

**Comment by amelio-vazquez-reina** [comment]
Thanks @benma Below is the trace for a test with  `vr/select-replace` with the python engine:

```
Debugger entered--Lisp error: (args-out-of-range #<buffer  *temp*> 0 0)
  match-string(1)
  vr--parse-replace("On GitHub as avazquez@xxx.com\n363 370 Zm9v\ncmVwbGFjZWQgMSBtYXRjaGVz\n")
  vr--run-command("python /Users/avazquez/.emacs.d/elpa/visual-regexp-steroids-20150411.416/regexp.py replace    --regexp \\(\\?m\\)arabica --replace foo" vr--parse-replace)
  ad-Advice-vr--get-replacements(#[(feedback feedback-limit) "\306\307\310\306\211\211r^Hq\210\311ed\")^Y^Z^[^\^]^^^[^^^\\3121\277^@\3131\263^@\314 ^V^\r^Hq\210^N^]b\210\315^^^^^N^^\205\255^@\3161C^@\3$
  apply(ad-Advice-vr--get-replacements #[(feedback feedback-limit) "\306\307\310\306\211\211r^Hq\210\311ed\")^Y^Z^[^\^]^^^[^^^\\3121\277^@\3131\263^@\314 ^V^\r^Hq\210^N^]b\210\315^^^^^N^^\205\255^@\316$
  vr--get-replacements(nil nil)
  vr--do-replace()
  vr/replace("arabica" "foo" 1 10602)
  funcall-interactively(vr/replace "arabica" "foo" 1 10602)
  call-interactively(vr/replace)
  vr/select-replace()
  funcall-interactively(vr/select-replace)
  call-interactively(vr/select-replace record nil)
  command-execute(vr/select-replace record)
  execute-extended-command(nil "vr/select-replace" "vr/select-re")
  funcall-interactively(execute-extended-command nil "vr/select-replace" "vr/select-re")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by benma** [comment]
Seems like your Python interpreter inserts "On GitHub as avazquez@xxx.com" on either stdout or stderr, which messes with the parsing.

Can you report the output of
`echo arabica | python /Users/avazquez/.emacs.d/elpa/visual-regexp-steroids-20150411.416/regexp.py replace    --regexp \(\?m\)arabica --replace foo`?

Does it contain the "On Github ..." string? If so, is it printed on stdout or stderr (if it is stderr, I can easily write a patch to fix it)? In any case, try to figure out where it comes from and get rid of it ;) I googled for that string but couldn't really find anything. 

What happens if you use python2 (python2.7.x interpreter) instead of python3?

**Comment by amelio-vazquez-reina** [comment]
Thank you @benma That did it! I removed the line that was printing that string to `stdout`. More specifically, I moved it from my `.zshenv` to `.zshrc` (`zsh` is my default shell), and that fixed it. I think I am all set! I appreciate your help on this. Thanks again!

**Comment by benma** [comment]
If you don't mind, please update the Stackoverflow post as solved.

**Comment by amelio-vazquez-reina** [comment]
Thank you @benma. Of course. I just updated the [Q&A](https://github.com/benma/visual-regexp-steroids.el/issues/13) with an answer and marked it as solved.
